//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public string HoVaTen { get; set; }
        public Nullable<System.DateTime> NSinh { get; set; }
        public string DThoai { get; set; }
        public string CMND { get; set; }
        public string DChi { get; set; }
        public int MaKH { get; set; }
    }
}
